/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  SnApp as SnApp
} from './components/sn-app/sn-app';

declare global {
  interface HTMLSnAppElement extends SnApp, HTMLStencilElement {
  }
  var HTMLSnAppElement: {
    prototype: HTMLSnAppElement;
    new (): HTMLSnAppElement;
  };
  interface HTMLElementTagNameMap {
    "sn-app": HTMLSnAppElement;
  }
  interface ElementTagNameMap {
    "sn-app": HTMLSnAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "sn-app": JSXElements.SnAppAttributes;
    }
  }
  namespace JSXElements {
    export interface SnAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SnGame as SnGame
} from './components/sn-game/sn-game';

declare global {
  interface HTMLSnGameElement extends SnGame, HTMLStencilElement {
  }
  var HTMLSnGameElement: {
    prototype: HTMLSnGameElement;
    new (): HTMLSnGameElement;
  };
  interface HTMLElementTagNameMap {
    "sn-game": HTMLSnGameElement;
  }
  interface ElementTagNameMap {
    "sn-game": HTMLSnGameElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "sn-game": JSXElements.SnGameAttributes;
    }
  }
  namespace JSXElements {
    export interface SnGameAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SnGameboard as SnGameboard
} from './components/sn-gameboard/sn-gameboard';

declare global {
  interface HTMLSnGameboardElement extends SnGameboard, HTMLStencilElement {
  }
  var HTMLSnGameboardElement: {
    prototype: HTMLSnGameboardElement;
    new (): HTMLSnGameboardElement;
  };
  interface HTMLElementTagNameMap {
    "sn-gameboard": HTMLSnGameboardElement;
  }
  interface ElementTagNameMap {
    "sn-gameboard": HTMLSnGameboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "sn-gameboard": JSXElements.SnGameboardAttributes;
    }
  }
  namespace JSXElements {
    export interface SnGameboardAttributes extends HTMLAttributes {
      animationPattern?: number[];
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
